# Generated by Django 3.2.4 on 2022-04-13 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('smsc', models.CharField(max_length=48)),
                ('ts', models.CharField(max_length=48)),
                ('destination', models.CharField(max_length=48)),
                ('source', models.CharField(max_length=48)),
                ('service', models.CharField(max_length=48)),
                ('url', models.CharField(max_length=48)),
                ('mask', models.PositiveIntegerField()),
                ('status', models.PositiveIntegerField()),
                ('boxc', models.CharField(max_length=48)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
